part of 'assets.dart';

abstract final class VectorAssets {
  static const String profileFilled = 'assets/vectors/profile_filled.svg';
  static const String visibility = 'assets/vectors/visibility.svg';
  static const String visibilityOff = 'assets/vectors/visibility_off.svg';
  static const String info = 'assets/vectors/info.svg';
  static const String check = 'assets/vectors/check.svg';
  static const String close = 'assets/vectors/close.svg';
  static const String logo = 'assets/vectors/logo.svg';
  static const String arrowsRight = 'assets/vectors/arrows_right.svg';
  static const String add = 'assets/vectors/add.svg';
  static const String taskSphereText = 'assets/vectors/task_sphere_text.svg';
  static const String spadesLines = 'assets/vectors/spades_lines.svg';
  static const String arrowBack = 'assets/vectors/arrow_back.svg';
  static const String mail = 'assets/vectors/mail.svg';
  static const String password = 'assets/vectors/password.svg';
  static const String fourDots = 'assets/vectors/four_dots.svg';
  static const String closeX = 'assets/vectors/close_x.svg';
  static const String nightMoon = 'assets/vectors/night_moon.svg';
  static const String search = 'assets/vectors/search.svg';
  static const String delete = 'assets/vectors/delete.svg';
  static const String setting = 'assets/vectors/setting.svg';
  static const String share = 'assets/vectors/share.svg';
  static const String priorityLow = 'assets/vectors/priority_low.svg';
  static const String priorityMedium = 'assets/vectors/priority_medium.svg';
  static const String priorityHigh = 'assets/vectors/priority_high.svg';
  static const String todo = 'assets/vectors/todo.svg';
  static const String done = 'assets/vectors/done.svg';
  static const String canceled = 'assets/vectors/canceled.svg';
  static const String noTasksGhost = 'assets/vectors/no_tasks_ghost.svg';
  static const String cancelFilled = 'assets/vectors/cancel_filled.svg';
  static const String menuDots = 'assets/vectors/menu_dots.svg';
  static const String reorder = 'assets/vectors/reorder.svg';
  static const String pointer = 'assets/vectors/pointer.svg';
  static const String moreVertical = 'assets/vectors/more_vertical.svg';
  static const String deleteOutlined = 'assets/vectors/delete_outlined.svg';
  static const String tickSquare = 'assets/vectors/tick_square.svg';
  static const String searchGhost = 'assets/vectors/search_ghost.svg';
  static const String arrowLeft = 'assets/vectors/arrow_left.svg';
  static const String arrowUpRight = 'assets/vectors/arrow_up_right.svg';
  static const String clock = 'assets/vectors/clock.svg';
  static const String calendar = 'assets/vectors/calendar.svg';
  static const String searchPlus = 'assets/vectors/search_plus.svg';
  static const String checkWeighted = 'assets/vectors/check_weighted.svg';
  static const String about = 'assets/vectors/about.svg';
  static const String arrowRight = 'assets/vectors/arrow_right.svg';
  static const String arrowUpRightWeighted =
      'assets/vectors/arrow_up_right_weighted.svg';
  static const String emailIcon = 'assets/vectors/email_icon.svg';
  static const String twitter = 'assets/vectors/twitter.svg';
  static const String whatsapp = 'assets/vectors/whatsapp.svg';
  static const String _helper = 'assets/vectors/.svg';
}
